# Generated by Django 2.1 on 2019-10-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fav_picture', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavPicture',
            new_name='FavPictureModel',
        ),
    ]
