# Generated by Django 2.1 on 2019-10-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fav_picture', '0002_auto_20191008_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favpicturemodel',
            name='fp_caption',
            field=models.TextField(max_length=500),
        ),
    ]
