# Generated by Django 2.1 on 2019-10-08 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fav_picture', '0003_auto_20191008_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='favpicturemodel',
            name='fp_created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favpicturemodel',
            name='fp_published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Published Date'),
        ),
        migrations.AlterField(
            model_name='favpicturemodel',
            name='fp_caption',
            field=models.TextField(help_text='Enter something will ya?', max_length=500, verbose_name='Fav Caption'),
        ),
    ]
