# Generated by Django 2.1 on 2019-10-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fav_picture', '0004_auto_20191008_0607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favpicturemodel',
            options={'get_latest_by': 'fp_published_date'},
        ),
    ]
